#!/bin/bash
#
# Run the old qemu-system-i386 from 18.04 outside of the dsl server
#

#
# use curses and tinfo libraries from 18.04 (main-net only)
#
# export LD_LIBRARY_PATH=/home/fac/wrc/lib/u1804

#
# other options:
#	-nographic
#	-display gtk
#


exec qemu-system-i386 \
    -d guest_errors \
	-serial mon:stdio \
	-drive file=usb.img,index=0,media=disk,format=raw
